from setuptools import setup, find_packages

setup(
    name="bwa-xai",
    version="0.1.0",
    author="Islam Mujahidul",
    author_email="mujahidul@student.tiu.ac.jp",
    description="Bootstrap Wasserstein Alignment for stable feature attribution",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/bootstrap-wasserstein-alignment",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "torch>=1.13.0",
        "captum>=0.6.0",
        "POT>=0.8.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
)
